### ISSUE TITLE
Modifying old scripts when using a machine with both GMT 5 and 6

### ISSUE THREAD

**Issue by melzhangmelzhang** [GenericMappingTools/2019-unavco-course#30]
Hi guys, during the GMT for Geodesy short course last week, Paul and Leo helped me install 'gmtswitch' so that I could toggle between GMT 5.4.5 and GMT 6.0.0rc3. Prior to the workshop, I had run a script for producing a figure; the script was written by someone who uses GMT 5.1.1, and I ran it (without any problems) using 5.4.5. Then, after the workshop, I noticed the script would not run when I toggled into 5.4.5. None of the GMT commands were being found.

After some troubleshooting we figured out that it would run if 'gmt' was appended before every GMT command, e.g. 'gmtset', 'psxy' etc., even though that was not needed before. We also found that the paper size and the figure did not fit well anymore, and only two-thirds of the figure would show on the paper. The original script had used 'gmtset' to change default settings, so we commented all of these out and did 'gmt defaults > gmt.conf', then edited gmt.conf to have the same paper size as the script originally specified (PS_MEDIA = 900 x 900), after which the figure was produced successfully, albeit without the custom parameters because all the 'gmtset' commands were commented out.

My question is what is the reason that, for example, 'gmt' needed to be added before every command when that wasn't a requirement for GMT 5 before, and how does it relate to the installation of 6.0.0rc3 and using gmtswitch? Moving forward, if I use GMT 5 scripts, will the scripts need to be edited in order to run properly even when I am toggled into 5.4.5 (basically will this scenario happen every time I use 5.4.5)?

**Comment by seisman** [comment]
In GMT4, all commands (e.g. psxy, pscoast) are executable programs. Sometimes, other software may also provide executable programs with the same names. It usually cause troubles, because when you run `psxy`, you don't know whether it comes from GMT or others.

To fix the namespace conflict, GMT5 only provides a single executable program, i.e. `gmt`. All GMT commands are now called GMT "modules". You need use `gmt psxy` to call the psxy module, instead of using `psxy`. That's why all GMT5 or GMT6 commands must start with `gmt`.

To not break older GMT4 scripts, we also provide some symbol links, so that you can still use `psxy` without the leading `gmt`. You can go to your GMT5.4.5 bin directory, and check if there are some symbol links like `psxy`. If not, you can run the script `share/gmt_links.sh` to create the symbol links for you.
